import type { Linter } from 'eslint'

export const base: Linter.Config = {
  plugins: ['sonar'],
  rules: {
    'sonar/argument-type': 2,
    'sonar/arguments-order': 2,
    'sonar/array-callback-without-return': 2,
    'sonar/bitwise-operators': 2,
    'sonar/call-argument-line': 2,
    'sonar/comma-or-logical-or-case': 2,
    'sonar/code-eval': 2,
    'sonar/declarations-in-global-scope': 1,
    'sonar/deprecation': 1,
    'sonar/different-types-comparison': 2,
    'sonar/for-in': 2,
    'sonar/for-loop-increment-sign': 2,
    'sonar/function-inside-loop': 2,
    'sonar/future-reserved-words': 1,
    'sonar/generator-without-yield': 2,
    'sonar/in-operator-type-error': 2,
    'sonar/inconsistent-function-call': 2,
    'sonar/label-position': 2,
    'sonar/new-operator-misuse': [2, { considerJSDoc: false }],
    'sonar/no-accessor-field-mismatch': 2,
    'sonar/no-alphabetical-sort': 2,
    'sonar/no-array-delete': 2,
    'sonar/no-associative-arrays': 2,
    'sonar/no-built-in-override': 2,
    'sonar/no-case-label-in-switch': 2,
    'sonar/no-commented-code': 1,
    'sonar/no-dead-store': 2,
    'sonar/no-delete-var': 2,
    'sonar/no-duplicate-in-composite': 2,
    'sonar/no-empty-collection': 2,
    'sonar/no-equals-in-for-termination': 1,
    'sonar/no-function-declaration-in-block': 1,
    'sonar/no-global-this': 1,
    'sonar/no-globals-shadowing': 1,
    'sonar/no-gratuitous-expressions': 1,
    'sonar/no-implicit-global': 2,
    'sonar/no-in-misuse': 2,
    'sonar/no-incorrect-string-concat': 1,
    'sonar/no-infinite-loop': 2,
    'sonar/no-invalid-await': 2,
    'sonar/no-invariant-returns': 1,
    'sonar/no-labels': 1,
    'sonar/no-misleading-array-reverse': 1,
    'sonar/no-nested-assignment': 1,
    'sonar/no-nested-incdec': 1,
    'sonar/no-new-symbol': 2,
    'sonar/no-parameter-reassignment': 1,
    'sonar/no-primitive-wrappers': 1,
    'sonar/no-redundant-assignments': 1,
    'sonar/no-redundant-optional': 1,
    'sonar/no-redundant-parentheses': 1,
    'sonar/no-reference-error': 2,
    'sonar/no-try-promise': 2,
    'sonar/no-undefined-argument': 1,
    'sonar/no-unenclosed-multiline-block': 1,
    'sonar/no-unthrown-error': 2,
    'sonar/no-useless-increment': 2,
    'sonar/non-existent-operator': 2,
    'sonar/operation-returning-nan': 2,
    'sonar/post-message': 1,
    'sonar/sonar-block-scoped-var': 1,
    'sonar/sonar-no-fallthrough': 1,
    'sonar/sonar-no-unused-vars': 2,
    'sonar/strings-comparison': 2,
    'sonar/super-invocation': 2,
    'sonar/unused-import': 2,
    'sonar/updated-const-var': 2,
    'sonar/updated-loop-counter': 1,
    'sonar/useless-string-operation': 2,
    'sonar/values-not-convertible-to-numbers': 1,
  },
}

export const recommended: Linter.Config = {
  ...base,
  rules: {
    ...base.rules,
    'sonar/array-constructor': 2,
    'sonar/class-prototype': 2,
    'sonar/destructuring-assignment-syntax': 2,
    'sonar/function-name': [2, { format: '^[a-z][a-zA-Z0-9]*$' }],
    'sonar/future-reserved-words': 2,
    'sonar/max-union-size': [1, 5],
    'sonar/misplaced-loop-counter': 2,
    'sonar/no-commented-code': 2,
    'sonar/no-equals-in-for-termination': 2,
    'sonar/no-for-in-iterable': 2,
    'sonar/no-ignored-return': 1,
    'sonar/no-incorrect-string-concat': 2,
    'sonar/no-invariant-returns': 2,
    'sonar/no-labels': 2,
    'sonar/no-misleading-array-reverse': 2,
    'sonar/no-nested-assignment': 2,
    'sonar/no-nested-incdec': 2,
    'sonar/no-nested-switch': 1,
    'sonar/no-parameter-reassignment': 2,
    'sonar/no-primitive-wrappers': 2,
    'sonar/no-redundant-assignments': 2,
    'sonar/no-redundant-optional': 2,
    'sonar/no-redundant-parentheses': 2,
    'sonar/no-return-type-any': 1,
    'sonar/no-undefined-argument': 2,
    'sonar/no-unenclosed-multiline-block': 2,
    'sonar/no-unused-function-argument': 1,
    'sonar/no-useless-intersection': 2,
    'sonar/no-variable-usage-before-declaration': 2,
    'sonar/non-number-in-arithmetic-expression': 1,
    'sonar/null-dereference': 2,
    'sonar/prefer-default-last': 1,
    'sonar/prefer-promise-shorthand': 2,
    'sonar/shorthand-property-grouping': 1,
    'sonar/sonar-block-scoped-var': 2,
    'sonar/sonar-no-fallthrough': 2,
    'sonar/updated-loop-counter': 2,
    'sonar/values-not-convertible-to-numbers': 2,
  },
}

export const strict: Linter.Config = {
  ...recommended,
  rules: {
    ...recommended.rules,
    'sonar/arguments-usage': 2,
    'sonar/class-name': 2,
    'sonar/conditional-indentation': 2,
    'sonar/confidential-information-logging': 2,
    'sonar/constructor-for-side-effects': 2,
    'sonar/content-length': 1,
    'sonar/content-security-policy': 1,
    'sonar/cookie-no-httponly': 2,
    'sonar/cookies': 2,
    'sonar/cors': 1,
    'sonar/csrf': 2,
    'sonar/disabled-auto-escaping': 2,
    'sonar/disabled-resource-integrity': 2,
    'sonar/dns-prefetching': 2,
    'sonar/encryption-secure-mode': 2,
    'sonar/encryption': 2,
    'sonar/file-name-differ-from-class': 2,
    'sonar/file-permissions': 2,
    'sonar/file-uploads': 2,
    'sonar/frame-ancestors': 2,
    'sonar/hashing': 2,
    'sonar/hidden-files': 2,
    'sonar/insecure-cookie': 2,
    'sonar/insecure-jwt-token': 2,
    'sonar/no-clear-text-protocols': 2,
    'sonar/no-hardcoded-credentials': 2,
    'sonar/no-hardcoded-ip': 2,
    'sonar/no-ignored-return': 2,
    'sonar/no-intrusive-permissions': 2,
    'sonar/no-implicit-dependencies': 2,
    'sonar/no-ip-forward': 2,
    'sonar/no-mime-sniff': 2,
    'sonar/no-mixed-content': 2,
    'sonar/no-referrer-policy': 2,
    'sonar/no-return-type-any': 2,
    'sonar/no-unsafe-unzip': 2,
    'sonar/no-weak-cipher': 2,
    'sonar/no-weak-keys': 2,
    'sonar/non-number-in-arithmetic-expression': 2,
    'sonar/os-command': 2,
    'sonar/prefer-default-last': 2,
    'sonar/post-message': 2,
    'sonar/process-argv': 2,
    'sonar/production-debug': 2,
    'sonar/pseudo-random': 2,
    'sonar/publicly-writable-directories': 2,
    'sonar/regular-expr': 2,
    'sonar/session-regeneration': 2,
    'sonar/sockets': 2,
    'sonar/sql-queries': 2,
    'sonar/standard-input': 2,
    'sonar/strict-transport-security': 2,
    'sonar/unverified-certificate': 2,
    'sonar/unverified-hostname': 2,
    'sonar/weak-ssl': 2,
    'sonar/web-sql-database': 2,
    'sonar/x-powered-by': 2,
    'sonar/xml-parser-xxe': 2,
    'sonar/xpath': 2,
  },
}
